name: huawei_push
description: Fixed Huawei Push Kit Flutter plugin with working background handler
version: 6.12.0+302

homepage: https://github.com/huawei/hms-flutter-plugin

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.hms.flutter.push
        pluginClass: PushPlugin
